cd Websites/t/tibristo/

cd 20140423_NTup_v1.0
mput index.html

mput SelectedElTrig/index.html
mput SelectedElTrig0BTag/index.html
mput SelectedElTrig1BTag/index.html
mput SelectedElTrig2BTag/index.html
mput SelectedElTrig2LBTag/index.html
mput SelectedElTrig2MBTag/index.html
mput SelectedElTrig3Jet/index.html
mput SelectedElTrig3Jet0BTag/index.html
mput SelectedElTrig3Jet1BTag/index.html
mput SelectedElTrig3Jet2BTag/index.html
mput SelectedElTrig3Jet2LBTag/index.html
mput SelectedElTrig3Jet2MBTag/index.html
mput SelectedElTrig4Jet/index.html
mput SelectedElTrig4Jet0BTag/index.html
mput SelectedElTrig4Jet1BTag/index.html
mput SelectedElTrig4Jet2BTag/index.html
mput SelectedElTrig4Jet2LBTag/index.html
mput SelectedElTrig4Jet2MBTag/index.html
mput SelectedElTrigMJFit/index.html
mput SelectedElTrigMJFit0BTag/index.html
mput SelectedElTrigMJFit1BTag/index.html
mput SelectedElTrigMJFit2BTag/index.html
mput SelectedElTrigMJFit2LBTag/index.html
mput SelectedElTrigMJFit2MBTag/index.html
mput SelectedMuTrig/index.html
mput SelectedMuTrig0BTag/index.html
mput SelectedMuTrig1BTag/index.html
mput SelectedMuTrig2BTag/index.html
mput SelectedMuTrig2LBTag/index.html
mput SelectedMuTrig2MBTag/index.html
mput SelectedMuTrig3Jet/index.html
mput SelectedMuTrig3Jet0BTag/index.html
mput SelectedMuTrig3Jet1BTag/index.html
mput SelectedMuTrig3Jet2BTag/index.html
mput SelectedMuTrig3Jet2LBTag/index.html
mput SelectedMuTrig3Jet2MBTag/index.html
mput SelectedMuTrig4Jet/index.html
mput SelectedMuTrig4Jet0BTag/index.html
mput SelectedMuTrig4Jet1BTag/index.html
mput SelectedMuTrig4Jet2BTag/index.html
mput SelectedMuTrig4Jet2LBTag/index.html
mput SelectedMuTrig4Jet2MBTag/index.html
mput SelectedMuTrigMJFit/index.html
mput SelectedMuTrigMJFit0BTag/index.html
mput SelectedMuTrigMJFit1BTag/index.html
mput SelectedMuTrigMJFit2BTag/index.html
mput SelectedMuTrigMJFit2LBTag/index.html
mput SelectedMuTrigMJFit2MBTag/index.html
