cd Websites/t/tibristo/

mkdir 20140423_NTup_v1.0
cd 20140423_NTup_v1.0
mkdir SelectedElTrig/
mkdir SelectedElTrig0BTag/
mkdir SelectedElTrig1BTag/
mkdir SelectedElTrig2BTag/
mkdir SelectedElTrig2LBTag/
mkdir SelectedElTrig2MBTag/
mkdir SelectedElTrig3Jet/
mkdir SelectedElTrig3Jet0BTag/
mkdir SelectedElTrig3Jet1BTag/
mkdir SelectedElTrig3Jet2BTag/
mkdir SelectedElTrig3Jet2LBTag/
mkdir SelectedElTrig3Jet2MBTag/
mkdir SelectedElTrig4Jet/
mkdir SelectedElTrig4Jet0BTag/
mkdir SelectedElTrig4Jet1BTag/
mkdir SelectedElTrig4Jet2BTag/
mkdir SelectedElTrig4Jet2LBTag/
mkdir SelectedElTrig4Jet2MBTag/
mkdir SelectedElTrigMJFit/
mkdir SelectedElTrigMJFit0BTag/
mkdir SelectedElTrigMJFit1BTag/
mkdir SelectedElTrigMJFit2BTag/
mkdir SelectedElTrigMJFit2LBTag/
mkdir SelectedElTrigMJFit2MBTag/
mkdir SelectedMuTrig/
mkdir SelectedMuTrig0BTag/
mkdir SelectedMuTrig1BTag/
mkdir SelectedMuTrig2BTag/
mkdir SelectedMuTrig2LBTag/
mkdir SelectedMuTrig2MBTag/
mkdir SelectedMuTrig3Jet/
mkdir SelectedMuTrig3Jet0BTag/
mkdir SelectedMuTrig3Jet1BTag/
mkdir SelectedMuTrig3Jet2BTag/
mkdir SelectedMuTrig3Jet2LBTag/
mkdir SelectedMuTrig3Jet2MBTag/
mkdir SelectedMuTrig4Jet/
mkdir SelectedMuTrig4Jet0BTag/
mkdir SelectedMuTrig4Jet1BTag/
mkdir SelectedMuTrig4Jet2BTag/
mkdir SelectedMuTrig4Jet2LBTag/
mkdir SelectedMuTrig4Jet2MBTag/
mkdir SelectedMuTrigMJFit/
mkdir SelectedMuTrigMJFit0BTag/
mkdir SelectedMuTrigMJFit1BTag/
mkdir SelectedMuTrigMJFit2BTag/
mkdir SelectedMuTrigMJFit2LBTag/
mkdir SelectedMuTrigMJFit2MBTag/
