cd Websites/t/tibristo/20140423_NTup_v1.0
mput SelectedElTrig/*
mput SelectedElTrig0BTag/*
mput SelectedElTrig1BTag/*
mput SelectedElTrig2BTag/*
mput SelectedElTrig2LBTag/*
mput SelectedElTrig2MBTag/*
mput SelectedElTrig3Jet/*
mput SelectedElTrig3Jet0BTag/*
mput SelectedElTrig3Jet1BTag/*
mput SelectedElTrig3Jet2BTag/*
mput SelectedElTrig3Jet2LBTag/*
mput SelectedElTrig3Jet2MBTag/*
mput SelectedElTrig4Jet/*
mput SelectedElTrig4Jet0BTag/*
mput SelectedElTrig4Jet1BTag/*
mput SelectedElTrig4Jet2BTag/*
mput SelectedElTrig4Jet2LBTag/*
mput SelectedElTrig4Jet2MBTag/*
mput SelectedElTrigMJFit/*
mput SelectedElTrigMJFit0BTag/*
mput SelectedElTrigMJFit1BTag/*
mput SelectedElTrigMJFit2BTag/*
mput SelectedElTrigMJFit2LBTag/*
mput SelectedElTrigMJFit2MBTag/*
mput SelectedMuTrig/*
mput SelectedMuTrig0BTag/*
mput SelectedMuTrig1BTag/*
mput SelectedMuTrig2BTag/*
mput SelectedMuTrig2LBTag/*
mput SelectedMuTrig2MBTag/*
mput SelectedMuTrig3Jet/*
mput SelectedMuTrig3Jet0BTag/*
mput SelectedMuTrig3Jet1BTag/*
mput SelectedMuTrig3Jet2BTag/*
mput SelectedMuTrig3Jet2LBTag/*
mput SelectedMuTrig3Jet2MBTag/*
mput SelectedMuTrig4Jet/*
mput SelectedMuTrig4Jet0BTag/*
mput SelectedMuTrig4Jet1BTag/*
mput SelectedMuTrig4Jet2BTag/*
mput SelectedMuTrig4Jet2LBTag/*
mput SelectedMuTrig4Jet2MBTag/*
mput SelectedMuTrigMJFit/*
mput SelectedMuTrigMJFit0BTag/*
mput SelectedMuTrigMJFit1BTag/*
mput SelectedMuTrigMJFit2BTag/*
mput SelectedMuTrigMJFit2LBTag/*
mput SelectedMuTrigMJFit2MBTag/*
