python analyseData.py --dnn-file=../boosted_framework/WTaggingNN/trained_full/config-trained-paramID_2mc15_nTrk_v3_bkg_v1ID_2.yaml --dnn-scaler=/Disk/ds-sopa-group/PPE/atlas/users/tibristo/boosted_framework/WTaggingNN/folds/AntiKt10LCTopoTrimmedPtFrac5SmallR20_13tev_mc15_nTrk_v3_400_1200_mw_mergedscaletrain_cv_002_scaler.pkl --bdt-file=evaluationObjects/paramID_0mc15_nTrk_v1_bkg_v4ID_2.pbz2 --data-input-file=data_vvjj.txt
#python analyseData.py --dnn-file=../boosted_framework/WTaggingNN/trained_full/config-trained-paramID_2mc15_nTrk_v1_bkg_v3ID_2.yaml --dnn-scaler=/Disk/ds-sopa-group/PPE/atlas/users/tibristo/boosted_framework/WTaggingNN/folds/AntiKt10LCTopoTrimmedPtFrac5SmallR20_13tev_mc15_nTrk_v1_400_1600_mw_mergedscaletrain_cv_002_scaler.pkl --bdt-file=evaluationObjects/paramID_2mc15_nTrk_v1_4_16_v3ID_2.pbz2 --data-input-file=W_GG_vvjj_test.txt
#python analyseData.py --dnn-file=../boosted_framework/WTaggingNN/trained_full/config-trained-paramID_2mc15_nTrk_v1_bkg_v3ID_2.yaml --dnn-scaler=/Disk/ds-sopa-group/PPE/atlas/users/tibristo/boosted_framework/WTaggingNN/folds/AntiKt10LCTopoTrimmedPtFrac5SmallR20_13tev_mc15_nTrk_v1_400_1600_mw_mergedscaletrain_cv_002_scaler.pkl --bdt-file=evaluationObjects/paramID_0mc15_nTrk_v1_4_16_v3ID_0.pbz2 --data-input-file=data_vvjj_test.txt

#python analyseData.py --dnn-file=../boosted_framework/WTaggingNN/trained_full/config-trained-paramID_2mc15_nTrk_v1_bkg_v4ID_2.yaml --dnn-scaler=/Disk/ds-sopa-group/PPE/atlas/users/tibristo/boosted_framework/WTaggingNN/folds/AntiKt10LCTopoTrimmedPtFrac5SmallR20_13tev_mc15_nTrk_v1_400_1600_mw_mergedscaletrain_cv_002_scaler.pkl --bdt-file=evaluationObjects/paramID_0mc15_nTrk_v1_bkg_v4ID_2.pbz2 --data-input-file=W_GG_vvjj.txt



# without nTracks
#python analyseData.py --dnn-file=../boosted_framework/WTaggingNN/trained_full/config-trained-paramID_0mc15_v3.2_bkg_v1ID_0.yaml --dnn-scaler=/Disk/ds-sopa-group/PPE/atlas/users/tibristo/boosted_framework/WTaggingNN/folds/AntiKt10LCTopoTrimmedPtFrac5SmallR20_13tev_mc15_v3_400_1600_mw_mergedscaletrain_cv_000_scaler.pkl --bdt-file=evaluationObjects/paramID_0mc15_v3.1_4_16_v1ID_0_full__tx_weightvalidation_jz5.pbz2 --data-input-file=W_GG_vvjj.txt

#python analyseData.py --dnn-file=../boosted_framework/WTaggingNN/trained_full/config-trained-paramID_0mc15_v3.2_bkg_v1ID_0.yaml --dnn-scaler=/Disk/ds-sopa-group/PPE/atlas/users/tibristo/boosted_framework/WTaggingNN/folds/AntiKt10LCTopoTrimmedPtFrac5SmallR20_13tev_mc15_v3_400_1600_mw_mergedscaletrain_cv_000_scaler.pkl --bdt-file=evaluationObjects/paramID_0mc15_v3.1_4_16_v1ID_0_full__tx_weightvalidation_jz5.pbz2 --data-input-file=data_vvjj.txt
